const express = require('express');
const cors = require('cors');

const app = express();
app.use(cors());
app.use(express.json());

app.post('/api/generate', (req, res) => {
  const { topic } = req.body;

  const blog = `
  🌟 Title: ${topic}

  Welcome to this blog post about "${topic}"! Let's explore the topic in detail.

  1. Introduction:
     ${topic} is an important subject in today's world. It plays a crucial role in various domains.

  2. Key Benefits:
     - Helps in personal development
     - Useful in modern technology
     - Improves overall productivity

  3. Real-World Impact:
     ${topic} is used in everyday applications and continues to grow in demand.

  4. Conclusion:
     Thank you for reading this blog on ${topic}. Stay tuned for more!

  ✍️ Generated by: AI Blog Writer (Free Version)
  `;

  res.json({ blog });
});

const PORT = 5000;
app.listen(PORT, () => {
  console.log(`✅ Fake AI server running at http://localhost:${PORT}`);
});
